### ISSUE TITLE
No .deb package for latest releases

### ISSUE THREAD

**Issue by gerdneuman** [myTonino/Tonino-App#1]
I wanted to install the latest release on Ubuntu 16.04 (32bit), but there's no deb package for the v1.0.17. Also not for v1.0.16. Only for the older v1.0.15 release.
https://github.com/myTonino/Tonino-App/releases

Saying you also support Linux means that there are also installable packages for it ;)

Can you please also release a deb package for the latest bugfix release? I will install v1.0.15 because I need it by Friday for a Cupping. Hope this will work also without problems

**Comment by myTonino** [comment]
Linux builds for v1.0.17 are now online.
