### ISSUE TITLE
App not running on MacOS Sierra 10.12

### ISSUE THREAD

**Issue by Toninoincanada** [myTonino/Tonino-App#3]
I am trying to install the app on my mac and getting the following error:

<img width="433" alt="screen shot 2016-10-17 at 8 06 13 am" src="https://cloud.githubusercontent.com/assets/22892475/19445823/e8cc11d6-9463-11e6-830e-c6d8b011fcbb.png">

Please also find attached the open console errors I am getting:

[Tonino Console.docx](https://github.com/myTonino/Tonino-App/files/534010/Tonino.Console.docx)

the mac is the following model: iMac (Retina 5K, 27-inch, Late 2015)

**Comment by myTonino** [comment]
On startup the Tonino app generates a font cache. If there are broken fonts installed on the system, this might fail. According to your console log there is at least a permission problem with a font file name WarnockPro-SemiboldItDisp.otf.

OS X comes with an application called Font Book that you can use to deactivate or remove problematic fonts that may cause instabilities on your system (such as the failure to start up some apps). Start Font Book, select all fonts, and run "Validate Fonts" from the File menu. Those fonts marked red should be removed.

**Comment by Toninoincanada** [comment]
Thanks for getting back to me, so I removed the fonts that were not validated, they are now all validated (see attached). I also removed the one called «WarnockPro-SemiboldItDisp.otf». I am still getting the same error (also attached) and I have attached the new console log in excel this time as it is more clear. It looks like line 2 may hold the key but I am no expert.

thanks

Carl Dube

**Comment by myTonino** [comment]
Cannot see the attachment. Could you just print that line 2 here in a comment?

**Comment by Toninoincanada** [comment]
> Here it is, also, try this new file
> 
> Thanks

Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

**Comment by Toninoincanada** [comment]
[Console Tonino.docx](https://github.com/myTonino/Tonino-App/files/535021/Console.Tonino.docx)

**Comment by myTonino** [comment]
I don't think that the part you copied has anything to do with this. In the Console log, there is this time also no trace from the Tonino app start, so this is not very helpful. 

The app runs successful under MacOS Sierra 10.12 on other configurations, so it must be something on your machine.

I have one idea: in case you have the iMac configuration with the i5 processor it could be that the compiled app uses a command that is not supported by that processor due to the use of a compiler optimisation setting generates op codes (for one lib) that are not supported by this one.

I uploaded a new Mac OS X build that comes without those optimisations. Could you please download the latest app version again and test again? If it fails again, please send the part of the console log that contains the Tonino app start up trial. If it works, just close the issue and I will build all future versions that way.

Thanks for your support!

**Comment by Toninoincanada** [comment]
default	07:46:34.472290 -0400	Tonino	Traceback (most recent call last):
default	07:46:34.472331 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 1429, in <module>
default	07:46:34.472348 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 973, in pickle_load
default	07:46:34.472367 -0400	Tonino	FileNotFoundError: [Errno 2] No such file or directory: '/Users/carldube/.matplotlib/fontList.py3k.cache'
default	07:46:34.472382 -0400	Tonino	
default	07:46:34.472398 -0400	Tonino	During handling of the above exception, another exception occurred:
default	07:46:34.472418 -0400	Tonino	
default	07:46:34.472449 -0400	Tonino	Traceback (most recent call last):
default	07:46:34.472479 -0400	Tonino	  File "/private/var/folders/9n/wxvvlyl16vj_l08w3s0k962w0000gn/T/AppTranslocation/E805FF07-8BF7-4C46-8D6F-2DACDBBFB40E/d/Tonino.app/Contents/Resources/__boot__.py", line 107, in <module>
default	07:46:34.472525 -0400	Tonino	    _run()
default	07:46:34.472547 -0400	Tonino	  File "/private/var/folders/9n/wxvvlyl16vj_l08w3s0k962w0000gn/T/AppTranslocation/E805FF07-8BF7-4C46-8D6F-2DACDBBFB40E/d/Tonino.app/Contents/Resources/__boot__.py", line 88, in _run
default	07:46:34.472571 -0400	Tonino	    exec(compile(source, path, 'exec'), globals(), globals())
default	07:46:34.472592 -0400	Tonino	  File "/private/var/folders/9n/wxvvlyl16vj_l08w3s0k962w0000gn/T/AppTranslocation/E805FF07-8BF7-4C46-8D6F-2DACDBBFB40E/d/Tonino.app/Contents/Resources/tonino.py", line 104, in <module>
default	07:46:34.472608 -0400	Tonino	    from lib import main
default	07:46:34.472636 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.472656 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.472679 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.472697 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.472719 -0400	Tonino	  File "lib/main.pyo", line 64, in <module>
default	07:46:34.472740 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.472759 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.472779 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.472794 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.472807 -0400	Tonino	  File "uic/__init__.pyo", line 25, in <module>
default	07:46:34.472820 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.472840 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.472859 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.472877 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.472895 -0400	Tonino	  File "uic/MainWindowUI.pyo", line 364, in <module>
default	07:46:34.472914 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.472932 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.472950 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.472969 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.472988 -0400	Tonino	  File "uic/mplwidget.pyo", line 45, in <module>
default	07:46:34.473006 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.473024 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.473043 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.473061 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.473079 -0400	Tonino	  File "matplotlib/backends/backend_qt5agg.pyo", line 13, in <module>
default	07:46:34.473098 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.473116 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.473133 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.473148 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.473162 -0400	Tonino	  File "matplotlib/figure.pyo", line 38, in <module>
default	07:46:34.473175 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.473188 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.473202 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.473215 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.473228 -0400	Tonino	  File "matplotlib/colorbar.pyo", line 36, in <module>
default	07:46:34.473241 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.473254 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.473267 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.473285 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.473304 -0400	Tonino	  File "matplotlib/contour.pyo", line 22, in <module>
default	07:46:34.473321 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
default	07:46:34.473339 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
default	07:46:34.473353 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
default	07:46:34.473370 -0400	Tonino	  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
default	07:46:34.473383 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 1439, in <module>
default	07:46:34.473396 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 1418, in _rebuild
default	07:46:34.473411 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 1068, in __init__
default	07:46:34.473424 -0400	Tonino	  File "matplotlib/font_manager.pyo", line 589, in createFontList
default	07:46:34.473437 -0400	Tonino	PermissionError: [Errno 13] Permission denied: '/Library/Fonts/WarnockPro-BoldCapt.otf'

**Comment by Toninoincanada** [comment]
Fixed, thanks !
