### ISSUE TITLE
Tonino app not seeing Tonino USB device

### ISSUE THREAD

**Issue by AdamBr70** [myTonino/Tonino-App#6]
Hi,
I recently purchased a new Mac, running the latest OS 12.0.1.  I can see the Tonino device in the system report connected to the USB but the Tonino App does not connect to the device.  This is the 1.0.22 version of the Tonino App.  Any ideas for a fix?  Everything had worked on my previous computer.

Regards,
AB

**Comment by MAKOMO** [comment]
Strange. I just tested on macOS 12.0.1 and the app connects successfully. Are you on a M1 Mac? Are you connecting via an USB-C hub?

**Comment by christopherferan** [comment]
Hey marko, I have this same issue. macOS 12.0.1 on an M1 Pro Mac connected via USB-C.

**Comment by MAKOMO** [comment]
Hm. We can not even test this for the lack of an M1 machine.

**Comment by deviantworld** [comment]
Same problem here. On an Apple Silicon (Macbook Pro M1 Max) no recognition of the tonino within the app. Also running Mac OS 12.2 but I guess it must be an issue with the new silicon architecture?

**Comment by MAKOMO** [comment]
Dear all, I am just looking into this and ask for your support as I still do not have access to any M1 hardware. Could you please answer me the following two questions:

1) do you connect the Tonino via an USB-C-to-USB adapter from Apple or from a 3rd party provider?

2) when you connect your Tonino via USB, do you see an FT231 entry in the system report (click the Apple menu item in the top left corner and choose "About This Mac") under Hardware >> USB >> USB 3.1 as in the attached screen shot?

Thanks a lot,
Marko

<img width="723" alt="Screenshot 2022-07-30 at 11 12 41" src="https://user-images.githubusercontent.com/13909011/181904315-820e7ccc-f7bd-4455-8e86-f052a51d01b9.png">

**Comment by christopherferan** [comment]
Hey @MAKOMO , yes—I'm using the Apple USB-C-to-USB adapter. When I plug in the Tonino, the name of the device pops up on the screen of the Tonino. 

Here's what I see under the system report:
<img width="678" alt="Screen Shot 2022-08-01 at 4 45 39 PM" src="https://user-images.githubusercontent.com/98068883/182243781-a8d0e6a7-b792-4fb8-9d1d-0102da62aaaa.png">

**Comment by christopherferan** [comment]
FTDI's site doesn't yet have a driver for the Apple ARM architecture: https://ftdichip.com/drivers/vcp-drivers/

**Comment by myTonino** [comment]
Dear Christopher,

thanks for digging into this and reporting. Very helpful! So it seems the macOS build-in FTDI driver is in place and does recognize the Tonino (otherwise that FT231 device would not be listed).

It seems that the serial lib build into the Tonino app is using an outdated macOS serial API and thus fails to connect.

I just uploaded a new Tonino app beta build using some newer infrastructure:
https://github.com/myTonino/Tonino-App/releases/tag/v1.0.23-beta

Could you test if this one connect to your Tonino?

Thanks a lot for your support,
Marko

**Comment by christopherferan** [comment]
@MAKOMO — working now. You're a wizard. Thanks!

**Comment by MAKOMO** [comment]
Thanks for that confirmation Chris! I will make a new release with this fix in short time. You can keep using this version which is also signed and notarized by Apple.
