### ISSUE TITLE
Modified Serial Port settings - serial.py - recompile from windows .bat file yields error and extremely large exe file

### ISSUE THREAD

**Issue by lsuess** [myTonino/Tonino-App#7]
I know this thread is a few years old, but I have been reading the documents and requirements for Windows 10 system. I was able to install the required python modules (matched the version numbers), but when compiling the .bat file for Windows I get a 255 MB .exe installer file (compared to the pre-compiled exe of 55 MB). When I run the exe installer, I receive the following error. Any guidance would be greatly appreciated.  (Python 3.10.6)  
![Unhandled_Exception_in_Script_lib_serialport](https://user-images.githubusercontent.com/80347096/211158261-bd635dfd-7395-4c9a-a2b1-19fee1fa08c9.png)

**Comment by myTonino** [comment]
Did you install the dependencies (see requirements-win.txt)? Note that the build script also assumes an installed NIS and Microsoft Visual C++ Redistributable.
